#!/usr/bin/env python3
"""
currency_tracker.py
───────────────────
Fetches today's and yesterday's USD exchange rates from the free
Frankfurter API (https://www.frankfurter.app), computes percentage
changes, writes a clean CSV report, and appends a structured log entry.

Currencies tracked: INR, AED, USD, EUR, GBP, BRL, MXN

Dependencies (all stdlib except 'requests'):
    pip install requests

Bonus – Windows Task Scheduler:
    To run every morning at 08:00, open Task Scheduler and create a
    Basic Task with the action:
        Program : C:\\Python312\\python.exe          (adjust to your path)
        Arguments: "C:\\path\\to\\currency_tracker.py"
    Trigger  : Daily, at 08:00 AM
    A ready-made .bat launcher is also generated by this script
    (currency_tracker_launcher.bat) so you can point the scheduler at
    the .bat instead of the .py for simpler configuration.
"""

import csv
import json
import logging
import os
import sys
from datetime import date, timedelta
from pathlib import Path

import requests

# ──────────────────────────────────────────────
# CONFIGURATION
# ──────────────────────────────────────────────

# Currencies we care about.  USD is the base, so its rate vs itself = 1.0.
CURRENCIES = ["INR", "AED", "USD", "EUR", "GBP", "BRL", "MXN"]

# Threshold (%) above which a change is flagged as "significant"
SIGNIFICANT_THRESHOLD = 0.5          # percent

# Base currency for all exchange rates
BASE_CURRENCY = "USD"

# Free API – no key required
API_BASE = "https://api.frankfurter.app"

# Output paths (same directory as this script by default)
SCRIPT_DIR  = Path(__file__).resolve().parent
REPORT_CSV  = SCRIPT_DIR / "exchange_rate_report.csv"
LOG_FILE    = SCRIPT_DIR / "currency_tracker.log"
LAUNCHER    = SCRIPT_DIR / "currency_tracker_launcher.bat"

# ──────────────────────────────────────────────
# LOGGING SETUP
# ──────────────────────────────────────────────

logging.basicConfig(
    level     = logging.INFO,
    format    = "%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt   = "%Y-%m-%d %H:%M:%S",
    handlers  = [
        # Append every run to the persistent log file
        logging.FileHandler(LOG_FILE, encoding="utf-8"),
        # Also mirror output to the console for interactive runs
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger("currency_tracker")


# ──────────────────────────────────────────────
# HELPERS
# ──────────────────────────────────────────────

def fetch_rates(target_date: date) -> dict[str, float]:
    """
    Query Frankfurter for rates on a specific date.

    Endpoint format: GET /YYYY-MM-DD?base=USD&symbols=INR,AED,...
    Returns a dict mapping currency code → rate (float).
    USD itself is added manually as 1.0.
    Raises requests.HTTPError on non-2xx responses.
    """
    # Build the symbol list, excluding the base (API would reject it)
    symbols = ",".join(c for c in CURRENCIES if c != BASE_CURRENCY)
    url     = f"{API_BASE}/{target_date.isoformat()}"
    params  = {"base": BASE_CURRENCY, "symbols": symbols}

    log.info("Fetching rates for %s from %s", target_date, url)

    response = requests.get(url, params=params, timeout=10)
    response.raise_for_status()          # bubble up HTTP errors

    data  = response.json()
    rates = data.get("rates", {})

    # The base currency by definition has a rate of 1.0 vs itself
    rates[BASE_CURRENCY] = 1.0

    log.info("Received %d rate(s): %s", len(rates), list(rates.keys()))
    return rates


def pct_change(today: float, yesterday: float) -> float | None:
    """
    Percentage change from yesterday to today.
    Returns None if yesterday is zero (division guard).
    """
    if yesterday == 0:
        return None
    return ((today - yesterday) / yesterday) * 100


# ──────────────────────────────────────────────
# CORE LOGIC
# ──────────────────────────────────────────────

def build_report() -> list[dict]:
    """
    Fetch today's and yesterday's rates, compute changes,
    and return a list of row dicts ready for CSV writing.
    """
    today     = date.today()
    yesterday = today - timedelta(days=1)

    # Fetch both days; collect errors without crashing the whole run
    errors = []

    try:
        rates_today = fetch_rates(today)
    except Exception as exc:
        log.error("Failed to fetch today's rates: %s", exc)
        errors.append(f"today: {exc}")
        rates_today = {}

    try:
        rates_yesterday = fetch_rates(yesterday)
    except Exception as exc:
        log.error("Failed to fetch yesterday's rates: %s", exc)
        errors.append(f"yesterday: {exc}")
        rates_yesterday = {}

    rows = []
    for currency in CURRENCIES:
        rate_t = rates_today.get(currency)
        rate_y = rates_yesterday.get(currency)

        # Compute % change only when both values are available
        if rate_t is not None and rate_y is not None:
            change = pct_change(rate_t, rate_y)
        else:
            change = None

        # Flag significant moves
        if change is not None and abs(change) > SIGNIFICANT_THRESHOLD:
            flag = "SIGNIFICANT"
        else:
            flag = ""

        rows.append({
            "currency"       : currency,
            "today_rate"     : f"{rate_t:.6f}"  if rate_t  is not None else "N/A",
            "yesterday_rate" : f"{rate_y:.6f}"  if rate_y  is not None else "N/A",
            "pct_change"     : f"{change:+.4f}" if change  is not None else "N/A",
            "significant"    : flag,
        })

    # Log a summary of this run
    fetched_currencies = list(rates_today.keys())
    log.info(
        "Run complete | date=%s | currencies_fetched=%s | errors=%s",
        today,
        fetched_currencies,
        errors if errors else "none",
    )

    return rows


def write_csv(rows: list[dict]) -> None:
    """
    Write (overwrite) the CSV report with today's data.
    Columns: currency, today_rate, yesterday_rate, pct_change, significant
    """
    fieldnames = ["currency", "today_rate", "yesterday_rate", "pct_change", "significant"]

    with open(REPORT_CSV, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    log.info("CSV report written → %s", REPORT_CSV)


def create_windows_launcher() -> None:
    """
    Emit a .bat file that Task Scheduler can call directly.
    Adjust PYTHON_EXE if your Python lives elsewhere.
    """
    python_exe  = sys.executable          # path of the current interpreter
    script_path = Path(__file__).resolve()

    bat_content = f"""@echo off
REM ─────────────────────────────────────────────────────────────
REM  currency_tracker_launcher.bat
REM  Called by Windows Task Scheduler to run the currency tracker.
REM
REM  HOW TO SCHEDULE:
REM   1. Open Task Scheduler → Create Basic Task
REM   2. Trigger  : Daily, 08:00 AM
REM   3. Action   : Start a program
REM      Program  : {LAUNCHER}
REM ─────────────────────────────────────────────────────────────

"{python_exe}" "{script_path}"
"""

    with open(LAUNCHER, "w", encoding="utf-8") as fh:
        fh.write(bat_content)

    log.info("Windows launcher written → %s", LAUNCHER)


# ──────────────────────────────────────────────
# ENTRY POINT
# ──────────────────────────────────────────────

def main() -> None:
    log.info("══════════════════════════════════════════")
    log.info("  Currency Tracker  |  base=%s", BASE_CURRENCY)
    log.info("══════════════════════════════════════════")

    rows = build_report()
    write_csv(rows)
    create_windows_launcher()

    # Pretty-print to console so the user sees results immediately
    print("\n" + "─" * 65)
    print(f"{'CURRENCY':<10} {'TODAY':>12} {'YESTERDAY':>12} {'% CHANGE':>10}  FLAG")
    print("─" * 65)
    for r in rows:
        print(
            f"{r['currency']:<10} {r['today_rate']:>12} {r['yesterday_rate']:>12} "
            f"{r['pct_change']:>10}  {r['significant']}"
        )
    print("─" * 65)
    print(f"\nReport saved : {REPORT_CSV}")
    print(f"Log file     : {LOG_FILE}")
    print(f"Win launcher : {LAUNCHER}")
    print()


if __name__ == "__main__":
    main()
